### ISSUE TITLE
Unresolved function or method getRectangle()

### ISSUE THREAD

**Issue by rtarnec** [sshniro/line-segmentation-algorithm-to-gcp-vision#1]
Hi, thanks for sharing your code.

I get an error at line 54 of coordinatesHelper.js with getRectangle that is not defined.

Do you have an idea how to solve that?

TIA

**Comment by sshniro** [comment]
The fix has been committed. Please do have a look.

**Comment by rtarnec** [comment]
Thanks for the update. It works now, you just have to add 
`return finalArray; `
at the end of the `mergeNearByWords` function.
