### ISSUE TITLE
How to use for new images

### ISSUE THREAD

**Issue by gvenkat21** [sshniro/line-segmentation-algorithm-to-gcp-vision#14]
Hi,

Can you please elaborate on how I can test this on my own images. I tried putting the images in "images" folder and the gcp-vision json output in "json" folder and ran `npm test`.

But it didnt do anything. Please help. I'm not able to debug as I'm not familiar with nodsJS.

Regards,
Gautam

**Comment by danbete** [comment]
you probably managed by now...
you can watch this to set up and return result object from vision api:
https://www.youtube.com/watch?time_continue=32&v=BFOeM8ATWdk

**Comment by sshniro** [comment]
Closing this. Thanks for the link to the tutorial @danbete.
