### ISSUE TITLE
output visualize

### ISSUE THREAD

**Issue by Ella77** [sshniro/line-segmentation-algorithm-to-gcp-vision#16]
<img width="437" alt="34940084-415cf57e-fa14-11e7-8099-ffa7fbce1b21" src="https://user-images.githubusercontent.com/42016485/61463326-14adb000-a96c-11e9-8060-6879d5f543f3.png">
 I'm implementing end to end line segmentation oct including wrapper for cloud Vision API.

Like the image attached, after you run this program, save it to image (with spatial nearby bounding box and line bounding box) with new bounding box.

**Comment by sshniro** [comment]
Hi @Ella77 ,
Are you referring to provide more meta data in the output such as the newly created bounding box ?

**Comment by Ella77** [comment]
> Hi @Ella77 ,
> Are you referring to provide more meta data in the algorithm output such as the newly created bounding box ? or to persist the newly created bounding box to the image it self ?

 I think the latter one. With new data, we can also show the bounding box with Tesco sample images.

**Comment by sshniro** [comment]
This should be done externally as the main focus on the library is to concat the lines only. I will add a separate issue to provide the coordinates of the merged lines so an external tool/implementation can make the visualization on the image. Thanks for the suggestions @Ella77 ! :)
